
package br.com.caelum.estoque;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StockEndpointWsService", targetNamespace = "http://caelum.com.br/stockws/v1", wsdlLocation = "http://localhost:8080/caelum-books-soap/StockEndpointWs?wsdl")
public class StockEndpointWsService
    extends Service
{

    private final static URL STOCKENDPOINTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STOCKENDPOINTWSSERVICE_EXCEPTION;
    private final static QName STOCKENDPOINTWSSERVICE_QNAME = new QName("http://caelum.com.br/stockws/v1", "StockEndpointWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/caelum-books-soap/StockEndpointWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOCKENDPOINTWSSERVICE_WSDL_LOCATION = url;
        STOCKENDPOINTWSSERVICE_EXCEPTION = e;
    }

    public StockEndpointWsService() {
        super(__getWsdlLocation(), STOCKENDPOINTWSSERVICE_QNAME);
    }

    public StockEndpointWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOCKENDPOINTWSSERVICE_QNAME, features);
    }

    public StockEndpointWsService(URL wsdlLocation) {
        super(wsdlLocation, STOCKENDPOINTWSSERVICE_QNAME);
    }

    public StockEndpointWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOCKENDPOINTWSSERVICE_QNAME, features);
    }

    public StockEndpointWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockEndpointWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StockEndpointWs
     */
    @WebEndpoint(name = "StockEndpointWsPort")
    public StockEndpointWs getStockEndpointWsPort() {
        return super.getPort(new QName("http://caelum.com.br/stockws/v1", "StockEndpointWsPort"), StockEndpointWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockEndpointWs
     */
    @WebEndpoint(name = "StockEndpointWsPort")
    public StockEndpointWs getStockEndpointWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://caelum.com.br/stockws/v1", "StockEndpointWsPort"), StockEndpointWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STOCKENDPOINTWSSERVICE_EXCEPTION!= null) {
            throw STOCKENDPOINTWSSERVICE_EXCEPTION;
        }
        return STOCKENDPOINTWSSERVICE_WSDL_LOCATION;
    }

}
